#!/bin/bash

if [ -f /etc/lsb-release ]; then
    sudo apt-get update \
    && sudo apt-get upgrade \
    && sudo apt install git wget curl zsh build-essential g++ \
        gcc libssl-dev libreadline-dev zlib1g-dev
fi

export ZSH_CUSTOM="${HOME}/.oh-my-zsh/custom"

# Install oh-my-zsh
sh -c \
  "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Install zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions \
  ${ZSH_CUSTOM}/plugins/zsh-autosuggestions

# Install zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
  ${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting

# Download gitster theme
curl 'https://raw.githubusercontent.com/shashankmehta/dotfiles/master/thesetup/zsh/.oh-my-zsh/custom/themes/gitster.zsh-theme' \
  --output "${ZSH_CUSTOM}/themes/gitster.zsh-theme"

# Install fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf \
  && ~/.fzf/install
