#!/bin/bash

if command -v apt-get > /dev/null; then
  # Ubuntu/Debian specific
  echo
  echo "BOOTSTRAP: Found apt-get; installing..."
  echo

  sudo apt-get update \
  && sudo apt-get upgrade \
  && sudo apt install git wget curl zsh build-essential g++ \
      gcc libssl-dev libreadline-dev zlib1g-dev
elif command -v pacman > /dev/null; then
  # Arch/Manjaro specific
  echo
  echo "BOOTSTRAP: Found pacman; installing..."
  echo

  if ! command -v yay > /dev/null; then
    sudo pacman -Syu --needed git gcc base-devel yay
  fi

  yay -Syu --needed wget curl zsh openssl readline
fi

# # Install oh-my-zsh
sh -c \
  "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Install zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions \
  ${ZSH_CUSTOM}/plugins/zsh-autosuggestions

# Install zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
  ${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting

# Download gitster theme
curl 'https://raw.githubusercontent.com/shashankmehta/dotfiles/master/thesetup/zsh/.oh-my-zsh/custom/themes/gitster.zsh-theme' \
  --output "${ZSH_CUSTOM}/themes/gitster.zsh-theme"

# Install fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf \
  && ~/.fzf/install
